### ISSUE TITLE
[BUG] Fix nodemon at container launch

### ISSUE THREAD

**Issue by Sigri44** [RealToken-Community/properties-map#1]
**Describe the bug**
Crash on start of the "backend" container

**To Reproduce**
1. docker compose up -d
2. Crash on backend

**Expected behavior**
```bash
> realt-properties-map-backend@1.1.0 dev
> nodemon --watch src src/index.ts -r ts-node/register --inspect=0.0.0.0:9229
sh: nodemon: not found
```

**Comment by ghost** [comment]
@Sigri44 I was unable to reproduce locally.
Can you describe the process in more details?
I tried to rebuild the image I had locally, but the backend always starts correctly.

Also, this issue shouldn't cause problems while integrating the project in RealT community projects.
The backend of this repository is only present to act as a proxy to RealT dashboard API. Without it, the API cannot be accessed.

In the version you'll deploy, the frontend just needs to target RealT dashboard API instead of this repo's backend API.

**Comment by daodevinc** [comment]
> @Sigri44 I was unable to reproduce locally. Can you describe the process in more details? I tried to rebuild the image I had locally, but the backend always starts correctly.
> 
> Also, this issue shouldn't cause problems while integrating the project in RealT community projects. The backend of this repository is only present to act as a proxy to RealT dashboard API. Without it, the API cannot be accessed.
> 
> In the version you'll deploy, the frontend just needs to target RealT dashboard API instead of this repo's backend API.

Hum hum,

I just clone git and run docker compose up -d

Try to change docker-compose config but same.

Can you prune your docker, and remove all node_module, and try again please ?

Oh right, i try it with direct access, thx !

**Comment by daodevinc** [comment]
Update, frontend with direct api access :

<img width="333" alt="image" src="https://github.com/RealToken-Community/properties-map/assets/9304947/9a13cc22-ca6b-4cf9-b699-6466e78daf75">

**Comment by daodevinc** [comment]
I think you don't have add "node_module" into .dockerignore so your build is working in local, but not anywhere.

**Comment by ghost** [comment]
Could be the issue. I'll check that and let you know

**Comment by mfrederic** [comment]
@Sigri44 I tried to clean up my docker, node_modules and everything that could impact the building and starting of the project.

Even rebuilding the project from 0 (from checking out the project and with nothing remaining in Docker), it still starts without problems.
So far, I haven't been able to reproduce the same issue.

**Comment by daodevinc** [comment]
Fixed ! Can't work with past docker config.

https://github.com/RealToken-Community/properties-map/commit/eafe2dc86d7d86191c7d5e70b86624b7cd5cc5ce
